### ISSUE TITLE
Launch problems

### ISSUE THREAD

**Issue by dmsergeevich63** [jameshilliard/jungo-image#1]
I want to dump the firmware, but an error occurs. I am using Python2.6.2
```
C:\Python26>jungo-image.py -d -p admin 192.168.0.135
  File "C:\Python26\jungo-image.py", line 268
    print(cmd, end=' ')
                  ^
SyntaxError: invalid syntax

```
```
C:\Python26>jungo-image-2.py -d -p admin 192.168.0.135
Traceback (most recent call last):
  File "C:\Python26\jungo-image-2.py", line 221, in <module>
    buf = tn.read_until("Username: ", 3)
  File "C:\Python26\lib\telnetlib.py", line 307, in read_until
    self.process_rawq()
  File "C:\Python26\lib\telnetlib.py", line 469, in process_rawq
    self.option_callback(self.sock, cmd, opt)
  File "C:\Python26\jungo-image-2.py", line 155, in telnet_option
    sock.sendall(telnetlib.IAC + c + option)
UnboundLocalError: local variable 'c' referenced before assignment

```

**Comment by jameshilliard** [comment]
> I am using Python2.6.2

Yeah, don't do that, use python3, I had ported that script to python3 but forgot to [update the docs](https://github.com/jameshilliard/jungo-image/commit/cdc8024e1e86688cf065ec4f510612783235fff4).
